# Theme
#remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Airpup'
description: 'Quiet, long-duration flight. Airpup is a kite balloon, not a drone. No registration required.'

# Images
avatar: 'avatar.png'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#facebook: ''
crowd-supply: 'https://www.crowdsupply.com/head-full-of-air/airpup'
blog_url: 'https://headfullofair.com/tags/airpup'
twitter: 'headfullofair'
#linkedin: ''
instagram: 'headfullofair'
#pinterest: ''
#youtube: ''
#github-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
#email: ''
#messenger: ''

# Advanced settings
#plugins:
#  - jekyll-remote-theme
