# Theme
#remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Airpup'
description: 'The loyal little lifter.'

# Images
avatar: 'avatar.png'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#facebook: ''
twitter: 'flyairpup'
#linkedin: ''
#instagram: ''
#pinterest: ''
#youtube: ''
#github-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
blog_url: 'https://headfullofair.com/tags/airpup'
#email: ''
#messenger: ''

# Advanced settings
#plugins:
#  - jekyll-remote-theme
